name: on-push-main

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  base:
    uses: sargonpiraev/ci/.github/workflows/on-push-main.yml@main
    secrets: inherit

  release:
    needs: base
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: sargonpiraev/ci/.github/actions/setup-node-npm-ci@main

      - run: npm run build

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
